"""chat conversations

Revision ID: 3100f692a8d0
Revises: 7af2c2624f88
Create Date: 2026-09-11 08:17:31.455243

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3100f692a8d0'
down_revision: str | None = '7af2c2624f88'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """اعمال تغییرات این نسخه."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.create_index('ix_chat_conversations_time', ['updated_at'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_messages_conversation', ['conversation_id', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """بازگرداندن تغییرات این نسخه."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_messages_conversation')

    op.drop_table('chat_messages')
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_conversations_time')

    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
