"""initial schema

Revision ID: 7af2c2624f88
Revises: 
Create Date: 2026-09-08 13:16:01.489264

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7af2c2624f88'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """اعمال تغییرات این نسخه."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('provider_type', sa.String(length=40), nullable=False),
    sa.Column('base_url', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('requires_api_key', sa.Boolean(), nullable=False),
    sa.Column('has_credentials', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('extra_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_providers_name'), ['name'], unique=True)

    op.create_table('application_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('logger_name', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_logs_level'), ['level'], unique=False)

    op.create_table('backup_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.String(length=400), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('backup_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('open_time', sa.Integer(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', 'timeframe', 'open_time', name='uq_candle_unique')
    )
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.create_index('ix_candles_lookup', ['exchange', 'symbol', 'timeframe', 'open_time'], unique=False)

    op.create_table('exchange_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('rest_url', sa.String(length=200), nullable=False),
    sa.Column('ws_url', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('has_credentials', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_second', sa.Integer(), nullable=False),
    sa.Column('request_timeout', sa.Integer(), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('extra_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exchange_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_providers_name'), ['name'], unique=True)

    op.create_table('indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('indicator', sa.String(length=40), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('latest_values', sa.JSON(), nullable=False),
    sa.Column('interpretation', sa.String(length=40), nullable=False),
    sa.Column('candle_time', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', 'timeframe', 'indicator', name='uq_indicator_unique')
    )
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=False),
    sa.Column('high_24h', sa.Float(), nullable=False),
    sa.Column('low_24h', sa.Float(), nullable=False),
    sa.Column('volume_24h', sa.Float(), nullable=False),
    sa.Column('turnover_24h', sa.Float(), nullable=False),
    sa.Column('change_percent', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', name='uq_market_data_symbol')
    )
    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_data_symbol'), ['symbol'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('report_type', sa.String(length=40), nullable=False),
    sa.Column('export_format', sa.String(length=10), nullable=False),
    sa.Column('file_path', sa.String(length=400), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('is_user_modified', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=True)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_min', sa.Float(), nullable=True),
    sa.Column('entry_max', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profits', sa.JSON(), nullable=False),
    sa.Column('risk_reward', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('trend', sa.String(length=20), nullable=False),
    sa.Column('market_structure', sa.String(length=20), nullable=False),
    sa.Column('timeframes', sa.JSON(), nullable=False),
    sa.Column('indicators_used', sa.JSON(), nullable=False),
    sa.Column('ai_provider', sa.String(length=50), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('invalidation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_direction'), ['direction'], unique=False)
        batch_op.create_index('ix_signals_lookup', ['symbol', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_symbol'), ['symbol'], unique=False)

    op.create_table('symbols',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('exchange_symbol', sa.String(length=40), nullable=False),
    sa.Column('base_asset', sa.String(length=20), nullable=False),
    sa.Column('quote_asset', sa.String(length=20), nullable=False),
    sa.Column('price_precision', sa.Integer(), nullable=False),
    sa.Column('quantity_precision', sa.Integer(), nullable=False),
    sa.Column('min_order_amount', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', name='uq_symbol_exchange')
    )
    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symbols_exchange'), ['exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_symbols_symbol'), ['symbol'], unique=False)

    op.create_table('signal_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('analysis_text', sa.Text(), nullable=False),
    sa.Column('market_snapshot', sa.JSON(), nullable=False),
    sa.Column('risk_assessment', sa.JSON(), nullable=False),
    sa.Column('ai_raw_response', sa.Text(), nullable=False),
    sa.Column('data_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_name', sa.String(length=60), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_name', 'symbol_id', name='uq_watchlist_symbol')
    )
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlists_list_name'), ['list_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """بازگرداندن تغییرات این نسخه."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlists_list_name'))

    op.drop_table('watchlists')
    op.drop_table('signal_analysis')
    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symbols_symbol'))
        batch_op.drop_index(batch_op.f('ix_symbols_exchange'))

    op.drop_table('symbols')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_symbol'))
        batch_op.drop_index('ix_signals_lookup')
        batch_op.drop_index(batch_op.f('ix_signals_direction'))

    op.drop_table('signals')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))

    op.drop_table('settings')
    op.drop_table('reports')
    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_data_symbol'))

    op.drop_table('market_data')
    op.drop_table('indicators')
    with op.batch_alter_table('exchange_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_providers_name'))

    op.drop_table('exchange_providers')
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.drop_index('ix_candles_lookup')

    op.drop_table('candles')
    op.drop_table('backup_history')
    with op.batch_alter_table('application_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_logs_level'))
        batch_op.drop_index(batch_op.f('ix_application_logs_created_at'))

    op.drop_table('application_logs')
    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_providers_name'))

    op.drop_table('ai_providers')
    # ### end Alembic commands ###
